Disallow spaces and other troublesome characters in environment names
wtsi-hgi/softpack-core pull request #40
Opened 2024-01-30 10:03 UTC by sersorrel

(and also actually mark failed environments – those with builder output but no module file – as failed)

2024-01-30 10:04 UTC, mjkw31 submitted a review, later dismissed
LGTM.

2024-01-31 09:25 UTC, sb10 requested changes
Doc update please

2024-01-31 09:25 UTC, sb10 commented on softpack_core/schemas/environment.py
> +        Checks that name has no spaces.
Checks that name consists only of alphanumerics, underscore and dash.

2024-01-31 09:44 UTC, sb10 approved these changes

2024-01-31 09:45 UTC, merged